server:
  port: 8081
spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/tests?autoReconnect=true&characterEncoding=UTF-8'
    username: postgres
    password: 1
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
